spring:
  kafka:
    bootstrap-servers: "localhost:9092" # Your local Docker.
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      auto-commit-interval: 100
      auto-offset-reset: latest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: "poc_group_id"
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

my:
  config:
    limit: 0
    topics:
      hot: "hot_topic"
      cold: "cold_topic"